name: Publish GH Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Get code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1

      - name: Install yarn
        run: npm install -g yarn
        
      - name: Build
        run: yarn build 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
